BEGIN_FUNCTION_MAP
.Feed, 해외주식주문체결(미국), AS1, key=8, group=1;
    BEGIN_DATA_MAP
    InBlock,입력,input;
    begin
    end
    OutBlock,출력,output;
    begin
		라인일련번호       , lineseq          , lineseq          , long  , 10;
		계좌번호           , accno            , accno            , char  , 11;
		조작자ID           , user             , user             , char  , 8; 
		헤더길이           , len              , len              , long  , 6; 
		헤더구분           , gubun            , gubun            , char  , 1; 
		압축구분           , compress         , compress         , char  , 1; 
		암호구분           , encrypt          , encrypt          , char  , 1; 
		공통시작지점       , offset           , offset           , long  , 3; 
		TRCODE             , trcode           , trcode           , char  , 8; 
		이용사번호         , comid            , comid            , char  , 3; 
		사용자ID           , userid           , userid           , char  , 16;
		접속매체           , media            , media            , char  , 2; 
		I/F일련번호        , ifid             , ifid             , char  , 3; 
		전문일련번호       , seq              , seq              , char  , 9; 
		TR추적ID           , trid             , trid             , char  , 16;
		공인IP             , pubip            , pubip            , char  , 12;
		사설IP             , prvip            , prvip            , char  , 12;
		처리지점번호       , pcbpno           , pcbpno           , char  , 3; 
		지점번호           , bpno             , bpno             , char  , 3; 
		단말번호           , termno           , termno           , char  , 8; 
		언어구분           , lang             , lang             , char  , 1; 
		AP처리시간         , proctm           , proctm           , long  , 9; 
		메세지코드         , msgcode          , msgcode          , char  , 4; 
		메세지출력구분     , outgu            , outgu            , char  , 1; 
		압축요청구분       , compreq          , compreq          , char  , 1; 
		기능키             , funckey          , funckey          , char  , 4; 
		요청레코드개수     , reqcnt           , reqcnt           , long  , 4; 
		예비영역           , filler           , filler           , char  , 6; 
		연속구분           , cont             , cont             , char  , 1; 
		연속키값           , contkey          , contkey          , char  , 18;
		가변시스템길이     , varlen           , varlen           , long  , 2; 
		가변해더길이       , varhdlen         , varhdlen         , long  , 2; 
		가변메시지길이     , varmsglen        , varmsglen        , long  , 2; 
		조회발원지         , trsrc            , trsrc            , char  , 1; 
		I/F이벤트ID        , eventid          , eventid          , char  , 4; 
		I/F정보            , ifinfo           , ifinfo           , char  , 4; 
		예비영역           , filler1          , filler1          , char  , 41;
		주문체결유형코드   ,sOrdxctPtnCode    ,sOrdxctPtnCode    ,char	 , 2;
		주문시장코드       ,sOrdMktCode       ,sOrdMktCode       ,char   , 2;
		주문유형코드       ,sOrdPtnCode       ,sOrdPtnCode       ,char   , 2;
		관리지점번호       ,sMgmtBrnNo        ,sMgmtBrnNo        ,char   , 3;
		계좌번호           ,sAcntNo           ,sAcntNo           ,char   , 20;
		계좌명             ,sAcntNm           ,sAcntNm           ,char   , 40;
		종목번호           ,sIsuNo            ,sIsuNo            ,char   , 12;
		종목명             ,sIsuNm            ,sIsuNm            ,char   , 40;
		주문번호           ,sOrdNo            ,sOrdNo            ,long   , 10;
		원주문번호         ,sOrgOrdNo         ,sOrgOrdNo         ,long   , 10;
		체결번호           ,sExecNO           ,sExecNO           ,long   , 10; 
		해외체결ID         ,sAbrdExecId       ,sAbrdExecId       ,long   , 18;
		주문수량           ,sOrdQty           ,sOrdQty           ,long   , 16;
		주문가             ,sOrdPrc           ,sOrdPrc           ,long   , 13;
		체결수량           ,sExecQty          ,sExecQty          ,long   , 16;
		체결가             ,sExecPrc          ,sExecPrc          ,long   , 13;
		정정확인수량       ,sMdfyCnfQty       ,sMdfyCnfQty       ,long   , 16;
		정정확인가         ,sMdfyCnfPrc       ,sMdfyCnfPrc       ,long   , 16;
		취소확인수량       ,sCancCnfQty       ,sCancCnfQty       ,long   , 16;
		거부수량           ,sRjtQty           ,sRjtQty           ,long   , 16;
		주문처리유형코드   ,sOrdTrxPtnCode    ,sOrdTrxPtnCode    ,long   , 4;
		복수주문일련번호   ,sMtiordSeqno      ,sMtiordSeqno      ,long   , 10;
		주문조건           ,sOrdCndi          ,sOrdCndi          ,char   , 1;
		호가유형코드       ,sOrdprcPtnCode    ,sOrdprcPtnCode    ,char   , 2;
		단축종목번호       ,sShtnIsuNo        ,sShtnIsuNo        ,long   , 9;
		운용지시번호       ,sOpDrtnNo         ,sOpDrtnNo         ,char   , 12;
		미체결수량(주문)   ,sUnercQty         ,sUnercQty         ,char   , 16;
		원주문미체결수량   ,sOrgOrdUnercQty   ,sOrgOrdUnercQty   ,char   , 16;
		원주문정정수량     ,sOrgOrdMdfyQty    ,sOrgOrdMdfyQty    ,long   , 16;
		원주문취소수량     ,sOrgOrdCancQty    ,sOrgOrdCancQty    ,long   , 16;
		주문평균체결가     ,sOrdAvrExecPrc    ,sOrdAvrExecPrc    ,long   , 13;
		주문금액           ,sOrdAmt           ,sOrdAmt           ,long   , 16;
		표준종목번호       ,sStdIsuNo         ,sStdIsuNo         ,long   , 12;
		매매구분           ,sBnsTp            ,sBnsTp            ,long   , 1;
		통신매체코드       ,sCommdaCode       ,sCommdaCode       ,char   , 2;
		주문계좌번호       ,sOrdAcntNo        ,sOrdAcntNo        ,char   , 20;
		집계지점번호       ,sAgrgtBrnNo       ,sAgrgtBrnNo       ,char   , 3;
		등록시장코드       ,sRegMktCode       ,sRegMktCode       ,char   , 2;
		현금증거금률       ,sMnyMgnRat        ,sMnyMgnRat        ,char   , 7;
		대용증거금률       ,sSubstMgnRat      ,sSubstMgnRat      ,char   , 9;
		현금체결금액       ,sMnyExecAmt       ,sMnyExecAmt       ,char   , 16;
		대용체결금액       ,sSubstExecAmt     ,sSubstExecAmt     ,char   , 16;
		수수료체결금액     ,sCmsnAmtExecAmt   ,sCmsnAmtExecAmt   ,long   , 16;
		전일재사용체결금액 ,sPrdayRuseExecVal ,sPrdayRuseExecVal ,char   , 16;
		금일재사용체결금액 ,sCrdayRuseExecVal ,sCrdayRuseExecVal ,char   , 16;
		실물체결수량       ,sSpotExecQty      ,sSpotExecQty      ,char   , 16;
		공매도체결수량     ,sStslExecQty      ,sStslExecQty      ,char   , 16;
		전략코드           ,sStrtgCode        ,sStrtgCode        ,char   , 6;
		그룹ID             ,sGrpId            ,sGrpId            ,char   , 20;
		주문회차           ,sOrdSeqno         ,sOrdSeqno         ,char   , 10;
		주문자ID           ,sOrdUserId        ,sOrdUserId        ,long   , 16;
		체결시각           ,sExecTime         ,sExecTime         ,long   , 9;
		거래소수신체결시각 ,sRcptExecTime     ,sRcptExecTime     ,long   , 9;
		거부사유           ,sRjtRsn           ,sRjtRsn           ,long   , 8;
		잔고수량           ,sSecBalQty        ,sSecBalQty        ,long   , 16;
		실물주문가능수량   ,sSpotOrdAbleQty   ,sSpotOrdAbleQty   ,long   , 16;
		주문가능재사용수량 ,sOrdAbleRuseQty   ,sOrdAbleRuseQty   ,long   , 16;
		변동수량           ,sFlctQty          ,sFlctQty          ,long   , 16;
		잔고수량(D2)       ,sSecBalQtyD2      ,sSecBalQtyD2      ,long   , 16;
		매도주문가능수량   ,sSellAbleQty      ,sSellAbleQty      ,long   , 16;
		미체결매도주문수량 ,sUnercSellOrdQty  ,sUnercSellOrdQty  ,long   , 16;
		평균매입가         ,sAvrPchsPrc       ,sAvrPchsPrc       ,long   , 13;
		매입금액           ,sPchsAmt          ,sPchsAmt          ,char   , 16;
		예수금             ,sDeposit          ,sDeposit          ,char   , 16;
		대용금             ,sSubstAmt         ,sSubstAmt         ,long   , 16;
		위탁현금증거금액   ,sCsgnMnyMgn       ,sCsgnMnyMgn       ,long   , 16;
		위탁대용증거금액   ,sCsgnSubstMgn     ,sCsgnSubstMgn     ,long   , 16;
		주문가능현금       ,sOrdAbleMny       ,sOrdAbleMny       ,long   , 16;
		주문가능대용금액   ,sOrdAbleSubstAmt  ,sOrdAbleSubstAmt  ,long   , 16;
		재사용가능금액     ,sRuseAbleAmt      ,sRuseAbleAmt      ,char   , 16;
		신용거래코드       ,sMgntrnCode       ,sMgntrnCode       ,char   , 3;
    end
    END_DATA_MAP
END_FUNCTION_MAP
