BEGIN_FUNCTION_MAP
	.Func,해외주식API마스터조회(g3190),g3190,attr,block,svr=GTS,headtype=A;
	BEGIN_DATA_MAP
	g3190InBlock,기본입력,input;
	begin
		지연구분,delaygb,delaygb,char,1;
		국가구분,natcode,natcode,char,2;
		거래소구분,exgubun,exgubun,char,1;
		조회갯수,readcnt,readcnt,long,4;
		연속구분,cts_value,cts_value,char,16;
	end
	g3190OutBlock,출력,output;
	begin
		지연구분,delaygb,delaygb,char,1;
		국가구분,natcode,natcode,char,2;
		거래소구분,exgubun,exgubun,char,1;
		연속구분,cts_value,cts_value,char,16;
		레코드카운트,rec_count,rec_count,long,7;
	end
	g3190OutBlock1,출력1,output,occurs;
	begin
		KEY종목코드,keysymbol,keysymbol,char,18;
		국가코드,natcode,natcode,char,2;
		거래소코드,exchcd,exchcd,char,2;
		종목코드,symbol,symbol,char,16;
		거래소종목코드,seccode,seccode,char,18;
		한글종목명,korname,korname,char,64;
		영문종목명,engname,engname,char,64;
		외환코드,currency,currency,char,4;
		ISIN,isin,isin,char,12;
		FLOATPOINT,floatpoint,floatpoint,char,1;
		업종코드,indusury,indusury,char,4;
		상장주식수,share,share,long,16;
		자본금,marketcap,marketcap,long,16;
		액면가,par,par,double,15.6;
		액면가외환코드,parcurr,parcurr,char,4;
		매수주문단위2,bidlotsize2,bidlotsize2,char,8;
		매도주문단위2,asklotsize2,asklotsize2,char,8;
		기준가,clos,clos,double,15.6;
		상장일자,listed_date,listed_date,char,8;
		만기일자,expire_date,expire_date,char,8;
		거래정지여부,suspend,suspend,char,1;
		영업일자,bymd,bymd,char,8;
		SELLONLY구분,sellonly,sellonly,char,8;
		인지세여부,stamp,stamp,char,1;
		TICKSIZETYPE,ticktype,ticktype,char,8;
		전일종가,pcls,pcls,double,15.6;
		VCM대상종목,vcmf,vcmf,char,1;
		CAS대상종목,casf,casf,char,1;
		POS대상종목,posf,posf,char,1;
		소수점매매가능종목,point,point,char,1;
	end
	END_DATA_MAP
END_FUNCTION_MAP

